[toolchain]
package_manager = "bun"

[features]
resolution = true
skip-lint = false

[programs.localnet]
opal = "8NCcxyAzKiAHxJ9DMnADtxShYutS9w81wHcXqgCavTBy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun test tests/opal.test.ts --timeout 60000"
